### ISSUE TITLE
Release 2.1.2 not handling mapped design space values

### ISSUE THREAD

**Issue by punchcutter** [LettError/MutatorMath#202]
With v2.1.2 I'm getting some fun interpolation:

<img width="1522" alt="Screen Shot 2020-04-13 at 15 56 38" src="https://user-images.githubusercontent.com/11257204/79258375-e3e9a100-7e3f-11ea-8603-c68fe530ebec.png">
Without any mapping things seem fine, but with mapping like this it doesn't work

        <axis default="80" maximum="125" minimum="80" name="width" tag="wdth">
            <map input="80"  output="350" /> 
            <map input="90"  output="480" /> 
            <map input="100" output="575" /> 
            <map input="125" output="850" /> 
        </axis>

Using the latest code it all seems fine so how about a new release? Any reason not to? @anthrotype

**Comment by anthrotype** [comment]
I don't know, maybe Erik fixed the issue?
We are no longer using mutatorMath as the primary library for interpolating UFOs in fontmake (we use varLib for that via fontmake.instantiator), so I am not following the developments of MutatorMath as closely as I used to.
I do remember that fontmake has a hack whereby when a mapping is present, it makes a temporary designspace file without the mapping before sending it to mutatormath, as a workaround for that issue.

**Comment by anthrotype** [comment]
it seems that @LettError tagged a 3.0 release without also bumping the version in setup.py (still at 2.1.2) so the automatic upload to PyPI was probably rejected since a package with that version already exists on PyPI.
I suggest you tag a 3.0.1 (and stick to the X.Y.Z semver style with three digits, like the previous tags), so that a new package is uploaded to PyPI.
